### ISSUE TITLE
Comments are not saved after VS CODE restart

### ISSUE THREAD

**Issue by garfildalex6** [JJK96/vscode-textfile-comments#1]
I really like your extension. I really need it, but my comments are not saved after restarting the application. I also noticed that the comments.json file is not being created either. Can you help me solve this problem?

**Comment by JJK96** [comment]
Hi! Thank you for your interest in this extension. It's been a while since I worked on this, and it is very much in alpha stage. Currently, I also do not use this extension myself, so I haven't tested it. 

Normally, comments should be saved to a file directly after saving a comment. So, restarting VS Code should not influence whether comments are saved or not. Maybe something goes wrong while loading the comments.json file when opening the workspace again. Possibly it is overwritten with an empty comments file or something.

I suggest cloning the repository locally and setting up a VSCode extension development environment. Then you should be able to view logs, debug the code and find whether `writeThreads` is called at the appropriate times. If you have any improvements, feel free to send a PR!
